name: Build and test
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request: 
    branches: 
      - develop
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3

      - name: Install fastlane
        run: gem install fastlane

      - name: Run tests
        run: cd AppExchange/; fastlane tests --verbose 
